// <auto-generated />
namespace RMTracker.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class db55 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(db55));
        
        string IMigrationMetadata.Id
        {
            get { return "202006090920066_db55"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
