// <auto-generated />
namespace RMTracker.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class db41 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(db41));
        
        string IMigrationMetadata.Id
        {
            get { return "202006010822213_db41"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
